# Test GET all contacts
GET http://localhost:3000/contacts HTTP/1.1

###

# Test GET single contact by ID
GET http://localhost:3000/contacts/67cebb692febcfd73db189e9 HTTP/1.1

###

# Test POST a new contact (Adding Michael Benson)
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
  "_id": "67cebb692febcfd73db189e9",
  "email": "adebensonkehinde@gmail.com",
  "username": "MichaelBenson",
  "name": "Michael Benson",
  "ip_address": "94.121.168.53"
}

###

# Test PUT (Update contact)
PUT http://localhost:3000/contacts/67cebb692febcfd73db189e9 HTTP/1.1
Content-Type: application/json

{
  "email": "updatedemail@example.com",
  "username": "UpdatedMichael",
  "name": "Michael Benson Updated",
  "ip_address": "192.168.1.1"
}

###

# Test DELETE a contact
DELETE http://localhost:3000/contacts/67cebb692febcfd73db189e9 HTTP/1.1
